### ISSUE TITLE
FEATURE REQUEST: Specify Server

### ISSUE THREAD

**Issue by rldaugherty** [raghavanand98/n8n-ntfy.sh#1]
This node is amazing, but is it possible to put a field in the configuration that allows you to specify a different server than ntfy.sh? I self-host a lot of my stuff, and it would be awesome to add this feature.

EDIT: I just noticed it on the roadmap. Following for further updates.

**Comment by cryingpotat0** [comment]
Should be done!

**Comment by benborges** [comment]
I'm seeing that it appears the feature is now done but I still don't see where I should specify it and where to handle my user access, this is a self-hosted private ntfy server, could you give a bit more indications?

**Comment by cryingpotat0** [comment]
Yup, you can put the private ntfy URL here: https://github.com/raghavanand98/n8n-ntfy.sh/commit/4d934389f7d1522d750333eaf45d26f518806212
