### ISSUE TITLE
API Authentication

### ISSUE THREAD

**Issue by rgolab** [raghavanand98/n8n-ntfy.sh#4]
Are you planning to add https://docs.ntfy.sh/subscribe/api/#authentication functionality to the node?

Temporary I added Authorization header to the request, but it'd be gr8 to have UI for configure credentials etc.

**Comment by skrollme** [comment]
How did you do this, @rgolab ? With the n8n-nodes-ntfy package? Or via a custom outgoing webhook?

**Comment by rgolab** [comment]
@skrollme I modified code of `n8n-nodes-ntfy` package - added header in the `dist/nodes/Ntfy/Ntfy.node.js` file

**Comment by skrollme** [comment]
Thanks @rgolab. Tried it by myself and it is working in my n8n instance. I will create a PullRequets out of my state

**Comment by skrollme** [comment]
See #6

**Comment by cryingpotat0** [comment]
Thanks for the fix @skrollme! I've been busy with other projects and haven't had time to work on this recently, so I appreciate the help.

**Comment by skrollme** [comment]
I say "thank you" for the plugin you created in the first place, @cryingpotat0 ❤️

**Comment by skrollme** [comment]
One additional question @cryingpotat0 : Do you plan to release a new version of the package (including the support for authentication) at npmjs? I'm asking since I plan to overhaul my n8n setup soon and it would be easier to simply install the module from npmjs :D

**Comment by cryingpotat0** [comment]
Done!

**Comment by skrollme** [comment]
Awesome, thank you, @cryingpotat0 👍
